name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      environment:
        required: true
        type: string
    outputs:
      image_tag:
        description: 'Git SHA to be used when pulling image in deployment workflow'
        value: ${{ env.IMAGE_TAG }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      image_tag: ${{ env.IMAGE_TAG }}

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIAT6ZY5G7PYD7WWAMG
          aws-secret-access-key: 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
          aws-region: eu-north-1

      - uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: 272312907743.dkr.ecr.eu-north-1.amazonaws.com
          ECR_REPOSITORY: parkguard-ecs-staging
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          if [ "${{ inputs.branch }}" == "development" ]; then
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:staging-$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:staging-$IMAGE_TAG
          fi
