name: Deploy to Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # 1️⃣ Build and Push Docker Image
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image-uri: ${{ steps.set_image_uri.outputs.image-uri }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: 
          aws-secret-access-key: 
          aws-region: eu-north-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Image Tag & URI
        id: set_image_uri
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          IMAGE_URI=
          echo "image-uri=$IMAGE_URI" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        env:
          IMAGE_URI: ${{ steps.set_image_uri.outputs.image-uri }}
        run: |
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

  # 2️⃣ Deploy to ECS
  ecs-deploy:
    name: ECS Staging Deployment
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      ECS_CLUSTER: Parkguard-ECS-Staging-Cluster
      ECS_SERVICE: 
      CONTAINER_NAME: webapp-container
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: 
          aws-secret-access-key: 
          aws-region: eu-north-1

      - name: Download current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition parkguard-ecs-staging-webapp-TD \
            --query taskDefinition > task-definition.json

      - name: Render new task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ needs.build-and-push.outputs.image-uri }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
