name: Deploy to Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    uses: Rafay-devsinc/insta-clone-1042-main/.github/workflows/build-and-push.yml@main
    with:
      branch: main
      environment: staging-deploy
    secrets: inherit

  ecs-deploy:
    name: ECS Staging Deployment
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      ECS_CLUSTER: Parkguard-ECS-Staging-Cluster
      ECS_SERVICE: parkguard-ecs-staging-webapp-TD-service-yyhah51y
      CONTAINER_NAME: webapp-container
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIAT6ZY5G7PYD7WWAMG
          aws-secret-access-key: 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
          aws-region: eu-north-1

      - name: Download Current Task Definition
        run: |
          aws ecs describe-task-definition \
            --task-definition parkguard-ecs-staging-webapp-TD \
            --query "taskDefinition" > task-definition.json

      - name: Render Task Definition with New Image
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        env:
           IMAGE_TAG: ${{ github.sha }}
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: 272312907743.dkr.ecr.eu-north-1.amazonaws.com/parkguard-ecs-staging:staging-${GITHUB_SHA}

      - name: Deploy to ECS Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          cluster: ${{ env.ECS_CLUSTER }}
          service: ${{ env.ECS_SERVICE }}
          wait-for-service-stability: true
