name: Deploy to Staging

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  deploy-staging:
    uses: Rafay-devsinc/insta-clone-1042-main/.github/workflows/build-and-push.yml@main
    with:
      branch: main
      environment: staging-deploy
    secrets: inherit

  ecs-deploy:
    name: ECS Staging Deployment
    needs: deploy-staging  # âœ… Reference the previous job output
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIAT6ZY5G7PYD7WWAMG
          aws-secret-access-key: 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
          aws-region: eu-north-1

      - name: Update Task Definition with New Image
        run: |
          IMAGE_TAG=${{ needs.deploy-staging.outputs.image_tag }}
          ECR_REGISTRY=272312907743.dkr.ecr.eu-north-1.amazonaws.com

          # Fetch current task definition
          aws ecs describe-task-definition \
            --task-definition parkguard-ecs-staging-webapp-TD \
            --query "taskDefinition" > task_definition.json

          # Update image
          jq --arg IMAGE "$ECR_REGISTRY/parkguard-ecs-staging:staging-$IMAGE_TAG" \
             '.containerDefinitions[0].image = $IMAGE' task_definition.json > new_task_definition.json

          # Register new revision
          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new_task_definition.json \
            --query "taskDefinition.taskDefinitionArn" --output text)

          # Update ECS service
          aws ecs update-service \
            --cluster Parkguard-ECS-Staging-Cluster \
            --service parkguard-ecs-staging-webapp-TD-service-yyhah51y \
            --task-definition $NEW_TASK_DEF_ARN
